# Generated by Django 4.0.4 on 2022-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0003_imagemodel_gray'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='edge',
            field=models.ImageField(default='Not Set', upload_to=''),
        ),
    ]
